WebsiteKinhDoanhCayCanh/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebsiteKinhDoanhCayCanh.Models
{
    public class GioHang
    {
        private MyDataEF db = new MyDataEF();
        [Display(Name = "Mã sản phẩm")]
        public string iIdSanPham { set; get; }

        [Display(Name = "Tên sản phẩm")]
        public string sTenSanPham { set; get; }

        [Display(Name = "Ảnh")]
        public string sHinh { set; get; }

        [Display(Name = "Giá bán")]
        public double dGia { set; get; }

        [Display(Name = "Giảm giá")]
        public int igiamGia { set; get; }

        [Display(Name = "Số lượng")]
        public int iSoLuong { set; get; }

        [Display(Name = "Thành tiền")]
        public double dThanhTien
        {
            get { return iSoLuong * (dGia - dGia * ((float)igiamGia / 100)); }
        }
        public GioHang(string Id)
        {
            iIdSanPham = Id;
            SanPham sp = db.SanPham.Single(n => n.id_SP == iIdSanPham);
            sTenSanPham = sp.tenSP;
            HinhAnhSP hsp = db.HinhAnhSP.FirstOrDefault(n => n.id_SP == iIdSanPham);
            sHinh = hsp.duongDan;
            dGia = double.Parse(sp.gia.ToString());
            iSoLuong = (int)sp.soLuong;
            igiamGia = (int)sp.phanTramGiamGia;
        }

    }
}

WebsiteKinhDoanhCayCanh/Controllers/GioHangsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using WebsiteKinhDoanhCayCanh.Message;
using WebsiteKinhDoanhCayCanh.Models;
using WebsiteKinhDoanhCayCanh.Others;


namespace WebsiteKinhDoanhCayCanh.Controllers
{
    public class GioHangsController : Controller
    {

        private MyDataEF db = new MyDataEF();

        public List<GioHang> layGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }

        public string AddToCart(string id, int soLuong)
        {

            List<GioHang> lstGioHang = layGioHang();
            GioHang sanPham = lstGioHang.Find(n => n.iIdSanPham == id);
            if (sanPham == null)
            {
                if (soLuong > 1)
                {
                    sanPham = new GioHang(id);
                    sanPham.iSoLuong = soLuong;
                    lstGioHang.Add(sanPham);
                    return lstGioHang.Count().ToString();
                }
                else
                {
                    sanPham = new GioHang(id);
                    sanPham.iSoLuong = 1;
                    lstGioHang.Add(sanPham);
                    return lstGioHang.Count().ToString();
                }

            }
            else
            {
                return "existed";
            }
        }

        private int TongSoLuongSanPham()
        {
            int tsl = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                tsl = lstGioHang.Sum(n => n.iSoLuong);
            }
            return tsl;
        }

        private int TongSoSanPham()
        {
            int tsl = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                tsl = lstGioHang.Count;
            }
            return tsl;
        }

        private long TongTien(string IdVoucher)
        {
            long tt = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (IdVoucher == null || IdVoucher == "")
            {
                if (lstGioHang != null)
                    tt = (long)lstGioHang.Sum(n => n.dThanhTien);
                return tt;
            }
            else
            {
                if (lstGioHang != null)
                {
                    var phamTramGiamGia = db.Voucher.Find(IdVoucher).phanTramGiamGia;
                    tt = (long)lstGioHang.Sum(n => n.dThanhTien);
                    tt -= (long)(tt * ((float)phamTramGiamGia) / 100);
                }
                return tt;

            }
        }

        public ActionResult GioHang(string IdVoucher)
        {
            List<GioHang> lstGioHang = layGioHang();
            ViewBag.TongSoLuongSanPham = TongSoLuongSanPham();
            ViewBag.TongTien = TongTien(IdVoucher);
            ViewBag.TongSoSanPham = TongSoSanPham();
            if (IdVoucher != null)
            {

                ViewBag.Voucher = IdVoucher;
            }
            else
            {
                ViewBag.Voucher = "";
            }
            return View(lstGioHang);
        }

        public ActionResult GioHangPartial()
        {
            ViewBag.TongSoSanPham = TongSoSanPham();
            return PartialView();
        }

        public ActionResult XoaGiohang(string iIdSanPham)
        {

            List<GioHang> lstGiohang = layGioHang();
            GioHang sanpham = lstGiohang.SingleOrDefault(n => n.iIdSanPham == iIdSanPham);
            if (lstGiohang != null)
            {
                lstGiohang.RemoveAll(n => n.iIdSanPham == iIdSanPham);
                Notification.set_flash("Đã xoá sản phẩm khỏi giỏ hàng!", "success");
                return RedirectToAction("GioHang");
            }
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapNhatGioHang(string id, FormCollection collection)
        {
            List<GioHang> lstGioHang = layGioHang();
            GioHang sanPham = lstGioHang.SingleOrDefault(n => n.iIdSanPham == id);

            if (sanPham != null)
            {
                SanPham sp = db.SanPham.FirstOrDefault(s => s.id_SP == id);
                var soLuong = int.Parse(collection["quantity"].ToString());

                if (soLuong > sp.soLuong)
                {
                    if (sp.soLuong >= 100)
                    {
                        sanPham.iSoLuong = 100;
                        Notification.set_flash("Chỉ được mua tối đa 100 sản phẩm cùng loại !", "warning");
                        return RedirectToAction("GioHang");
                    }
                    else
                    {
                        sanPham.iSoLuong = (int)sp.soLuong;
                        Notification.set_flash("Sản phẩm hiện có chỉ còn lại: " + sp.soLuong + " !", "warning");
                        return RedirectToAction("GioHang");
                    }
                }
                else
                {
                    if (soLuong <= 100)
                    {
                        sanPham.iSoLuong = soLuong;
                        Notification.set_flash("Cập nhật giỏ hàng thành công!", "success");
                    }
                    else
                    {
                        sanPham.iSoLuong = 100;
                        Notification.set_flash("Chỉ được mua tối đa 100 sản phẩm cùng loại !", "warning");
                        return RedirectToAction("GioHang");
                    }
                }
                //sanPham.giamGia = double.Parse((soLuong * sp.GiamGia).ToString());
            }

            return RedirectToAction("GioHang");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<GioHang> lstGioHang = layGioHang();
            lstGioHang.Clear();
            Notification.set_flash("Đã xoá tất cả sản phẩm trong giỏ hàng!", "success");
            return RedirectToAction("GioHang");
        }


        //Dặt hàng
        [HttpGet]
        public ActionResult DatHang(string IdVoucher)
        {
            if (TongTien("") == 0)
            {
                return RedirectToAction("GioHang");
            }
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Login", "Account");
            }
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "SanPhams");
            }

            List<GioHang> lstGioHang = layGioHang();
            ViewBag.TongSoLuongSanPham = TongSoLuongSanPham();
            ViewBag.TongTien = TongTien(IdVoucher);
            ViewBag.TongSoSanPham = TongSoSanPham();
            ViewBag.Voucher = IdVoucher;

            return View(lstGioHang);
        }

        public ActionResult DatHang(FormCollection collection)
        {

            DonHang dh = new DonHang();
            Models.LinQ.User kh = (Models.LinQ.User)Session["TaiKhoan"];
            List<GioHang> gh = layGioHang();
            var ngaygiao = String.Format("{0:dd/MM/yyyy}", collection["NgayGiao"]);
            dh.id_User = kh.Id;
            dh.ngayDat = DateTime.Now;
            dh.ngayGiao = DateTime.Parse(ngaygiao);
            dh.trangThaiGiaoHang = "0";
            dh.trangThaiThanhToan = false;
            dh.phuongThucThanhToan = "0";

            var voucher = collection["Voucher"];
            dh.diaChiGiao = Request["txtAddress"].ToString() + "";
            if (voucher == "" || voucher == null)
            {
                dh.id_Voucher = null;
                dh.tongTien = TongTien("");
            }
            else
            {
                dh.id_Voucher = voucher;
                dh.tongTien = TongTien(voucher);

                var id_curentUser = System.Web.HttpContext.Current.User.Identity.GetUserId();
                UserVoucher updateVC = db.UserVoucher.Where(p => p.id_User == id_curentUser & p.id_voucher == voucher).FirstOrDefault();
                updateVC.soLuotConLai = 0;
            }
            db.DonHang.Add(dh);
            foreach (var item in gh)
            {
                CTDH ctdh = new CTDH();
                ctdh.id_DH = dh.id_DH;
                ctdh.id_SP = item.iIdSanPham;
                ctdh.soLuong = item.iSoLuong;
                ctdh.thanhTien = ((long)item.dThanhTien);
                SanPham sanPham = db.SanPham.Single(n => n.id_SP == item.iIdSanPham);
                sanPham.soLuong -= item.iSoLuong;
                db.CTDH.Add(ctdh);
            }
            db.SaveChanges();
            Session["GioHang"] = null;

            String content = System.IO.File.ReadAllText(Server.MapPath("~/Others/Checkout.html"));
            content = content.Replace("{{CustomerName}}", kh.FullName);
            content = content.Replace("{{Phone}}", kh.PhoneNumber);
            content = content.Replace("{{Email}}", kh.Email);
            content = content.Replace("{{Address}}", dh.diaChiGiao);
            content = content.Replace("{{NgayDat}}", dh.ngayDat.ToString());
            content = content.Replace("{{NgayGiao}}", String.Format("{0:dd/MM/yyyy}", dh.ngayGiao).ToString());
            content = content.Replace("{{Total}}", String.Format("{0:0,0}", dh.tongTien).ToString());
            var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

            new MailHelper().sendMail(kh.Email, "Đơn hàng mới từ Cây Cảnh AT - Trees", content);

WebsiteKinhDoanhCayCanh/Views/GioHangs/GioHang.cshtml
@model IEnumerable<WebsiteKinhDoanhCayCanh.Models.GioHang>
@using WebsiteKinhDoanhCayCanh.Models;
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ApplicationUser userLogin = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
}

<body>
    <div style="font-family: 'Sans-serif'">
        <div class="hero-wrap hero-bread" style="background-image: url('/Template/img/banner-img.jpg');opacity:0.9" ;>
            <div>
                <div class="container">
                    <div class="row no-gutters slider-text align-items-center justify-content-center">
                        <div class="col-md-9 ftco-animate text-center bg-text">
                            <h1 class="mb-0 bread" style="color: antiquewhite; font-family: 'cursive', 'Amatic SC','Liberation Mono'; ">GIỎ HÀNG</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Model.Count() != 0)
    {
        <section class="ftco-section ftco-cart">
            <div class="container">
                <h2 style=" text-align:center; color:green">Giỏ hàng của bạn</h2>
                <div class="row">

                    <div class="col-md-12 ftco-animate">
                        <div class="cart-list">
                            <table class="table">
                                <thead class="thead-primary">
                                    <tr class="text-center">
                                        <th></th>
                                        <th>STT</th>
                                        <th>Tên sản phẩm</th>
                                        <th>Hình ảnh</th>
                                        <th>Giá</th>
                                        <th>Giảm giá</th>
                                        <th>Số lượng</th>
                                        <th>Số tiền</th>
                                    </tr>
                                </thead>
                                @{
                                    int index = 0;
                                    foreach (var item in Model)
                                    {
                                        index++;
                                        <tbody>

                                            @using (Html.BeginForm("CapNhatGioHang", "GioHangs", new { @id = item.iIdSanPham }, FormMethod.Post, new { @id = "target-form" + "-" + item.iIdSanPham }))
                                            {
                                                <tr class="text-center">
                                                    <td class="product-remove"><a href="@Url.Action("XoaGioHang", "GioHangs", new { @iIdSanPham = item.iIdSanPham })"> <i class="ion-ios-trash" style="color:red;font-size:20px;font-weight:bold"></i></a></td>
                                                    <td>@index</td>
                                                    <td class="product-name">
                                                        <h3><a href="/SanPhams/Details/@item.iIdSanPham">@item.sTenSanPham</a></h3>
                                                    </td>
                                                    <td class="image-prod"><a href="/SanPhams/Details/@item.iIdSanPham"><div class="img" style="background-image:url('@item.sHinh');"></div></a> </td>



                                                    <td class="price">@String.Format("{0:0,0}", item.dGia)&#8363;</td>
                                                    <td class="sale">
                                                        @if (item.igiamGia > 0)
                                                        {
                                                            <strong>-@item.igiamGia%</strong>
                                                        }
                                                    </td>
                                                    <td class="quantity">
                                                        <div class="input-group mb-3">
                                                            <input id="quantity-@item.iIdSanPham" type="number" name="quantity" class="quantity form-control input-number" value="@item.iSoLuong" min="1" max="100" maxlength="3"
                                                                   onchange="updateGioHang('target-form-@item.iIdSanPham', this.id ,this.value)" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1').replace('.','');" />
                                                        </div>
                                                    </td>

                                                    <td class="total-price" style="color:red"><strong>@String.Format("{0:0,0}", item.dThanhTien)&#8363;</strong> </td>

                                                </tr><!-- END TR-->
                                            }
                                        </tbody>
                                    }}
                            </table>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center" style="width:100%;margin-top:25px;">
                        <a class="btn btn-primary py-3 px-4" href="@Url.Action("XoaTatCaGioHang", "GioHangs")"><i class="ion-ios-trash" style="color:red;font-size:20px;font-weight:bold;"></i>&ensp;Xóa tất cả sản phẩm.</a>
                    </div>
                </div>
                <div class="row justify-content-end">
                    <div class="col-lg-6 mt-5 cart-wrap ftco-animate">
                        <hr />
                        <div>
                            <p><a href="@Url.Action("Index", "Home")" class="btn btn-light py-3 px-4 "><img src="~/Template/img/home.png" width="25" height="25" ; />&ensp; Quay lại trang chủ </a></p>
                        </div>
                    </div>


                    <div class="col-lg-6 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3 style="color:green">Hóa đơn</h3>
                            <p class="d-flex">
                                <span> Tổng số sản phẩm</span>
                                <strong>@ViewBag.TongSoSanPham</strong>
                            </p>
                            <p class="d-flex">
                                <span> Tổng số lượng sản phẩm</span>
                                <strong>@ViewBag.TongSoLuongSanPham</strong>
                            </p>
                            <p class="d-flex">
                                <span>Giảm giá:</span>
                                <span style="color:red"><strong>-@String.Format("{0:0,0}", Model.Sum(p => (p.dGia * p.iSoLuong)) - ViewBag.TongTien)&#8363;</strong></span>
                            </p>
                            @if (userLogin != null)
                            {
                                int flag = 0;
                                MyDataEF db = new MyDataEF();
                                DateTime currentDate = DateTime.Today;
                                var lstVoucher = db.UserVoucher.Where(p => p.id_User == userLogin.Id & p.soLuotConLai > 0 & p.Voucher.thoiGianBatDau <= currentDate & currentDate <= p.Voucher.thoiGianKetThuc).ToList();
                                if (lstVoucher.Count > 0)
                                {
                                    <p class="d-flex">
                                        <span>Voucher:</span>
                                        <select id="Voucher" name="Voucher" onchange="apDungVoucher(this.value)">
                                            <option selected value="">Không áp dụng</option>
                                            @foreach (var item in lstVoucher)
                                            {

                                                if (item.id_voucher == ViewBag.Voucher)
                                                {
                                                    <option selected value="@item.id_voucher">(Giảm @item.Voucher.phanTramGiamGia%) - @item.Voucher.tenVoucher</option>
                                                }
                                                else
                                                {
                                                    <option value="@item.id_voucher">(Giảm @item.Voucher.phanTramGiamGia%) - @item.Voucher.tenVoucher</option>
                                                }

                                            }

                                        </select>
                                    </p>
                                }
                                else
                                {
                                    <p class="d-flex">
                                        <span>Voucher:</span>
                                        <select id="Voucher" name="Voucher" onchange="apDungVoucher(this.value)">
                                            <option selected value="">Hiện bạn chưa có voucher nào!</option>
                                        </select>
                                    </p>

                                }
                            }
                            <hr>
                            <p class="d-flex total-price">
                                <span style="font-weight:bold;font-size:18px">Tổng tiền</span>
                                <span style="color:red; font-size:18px"><strong>@String.Format("{0:0,0}", ViewBag.TongTien)&#8363;</strong></span>
                            </p>
                        </div>
                        <p><a href="@Url.Action("DatHang","GioHangs",new { @IdVoucher = ViewBag.Voucher })" class="btn btn-primary py-3 px-4"><i class="icon-shopping_cart"></i> Đặt hàng  </a></p>
                    </div>
                </div>
            </div>
        </section>
    }
    else
    {
        <div style="display: flex; flex-direction: column;align-items:center">
            <br />
            <div>
                <img src="~/Template/img/icon-cart.png" alt="thumbnail" width="300" style="margin: auto" />
            </div>
            <h2 style="color: #d45353e8; font-weight: 600">Oops! Chưa có sản phầm nào!</h2>

        </div>
        <div style="margin: 20px 0 100px 0 ">
            <div class="row">
                <div class="col-lg-12">
                    <div class="" style="text-align:center">
                        <a href="@Url.Action("Index", "Home")" class="btn btn-primary py-3 px-5"><span class="icon-shopping_cart"></span>&nbsp; Mua sắm ngay thôi! </a>
                    </div>
                </div>
            </div>
        </div>
    }

    <script>
        function updateGioHang(idForm, idInput, val) {
            if (val <= 0 || val == '') {
                document.getElementById(idInput).value = 1;
            }
            if (val.length > 3) {
                document.getElementById(idInput).value = 101;
            }
            document.getElementById(idForm).submit();
        }

        function apDungVoucher(val) {
            window.location.assign(location.href+'?IdVoucher=' + val)
        };
    </script>
</body>

WebsiteKinhDoanhCayCanh/Views/GioHangs/GiohangPartial.cshtml
<li class="nav-item cta cta-colored"><a href="@Url.Action("GioHang", "GioHangs")" class="nav-link"><span class="icon-shopping_cart"></span><span id="cart">&ensp;@ViewBag.TongSoSanPham</span></a></li>