WebsiteKinhDoanhCayCanh/Models/DonHang.cs
namespace WebsiteKinhDoanhCayCanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("DonHang")]
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            CTDH = new HashSet<CTDH>();
        }

        [Key]
        public int id_DH { get; set; }

        [Column(TypeName = "date")]
        public DateTime? ngayDat { get; set; }

        [Column(TypeName = "date")]
        public DateTime? ngayGiao { get; set; }

        public Boolean trangThaiThanhToan { get; set; }

        [StringLength(1)]
        public string trangThaiGiaoHang { get; set; }

        [StringLength(1)]
        public string phuongThucThanhToan { get; set; }

        public long? tongTien { get; set; }

        [StringLength(250)]
        public string diaChiGiao { get; set; }

        [StringLength(128)]
        public string id_User { get; set; }

        [StringLength(10)]
        public string id_Voucher { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDH { get; set; }

        public virtual Voucher Voucher { get; set; }
        //public virtual ICollection<ApplicationUser> Users { get; set; }

        /*        public static List<DonHang> getAll(String searchKey)
                {
                    MyDataEF db = new MyDataEF();
                    searchKey = searchKey + "";
                    //List<ChiTietDonHang> list = db.ChiTietDonHang.Where(a => a.SanPham.Ten.Contains(keyWord) && a.Soluong > 0).ToList();
                    //return db.DonHang.ToList();
                    return db.DonHang.Where(p => p.diaChiGiao.Contains(searchKey)).ToList();
                }*/
    }
}

WebsiteKinhDoanhCayCanh/Models/OtherModels/DonHangViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebsiteKinhDoanhCayCanh.Models.OtherModels
{
    public class DonHangViewModel
    {
        public LinQ.DonHang DonHang { get; set; }
        public List<CTDH> CTDH { get; set; }
    }
}

WebsiteKinhDoanhCayCanh/Controllers/DonHangsController.cs
using ClosedXML.Excel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteKinhDoanhCayCanh.Models;
using WebsiteKinhDoanhCayCanh.Models.LinQ;
using WebsiteKinhDoanhCayCanh.Models.OtherModels;
using DataTable = System.Data.DataTable;

namespace WebsiteKinhDoanhCayCanh.Controllers
{
    public class DonHangsController : Controller
    {
        private MyDataEF db = new MyDataEF();
        private MyDBDataContext data = new MyDBDataContext();
        private ApplicationDbContext dataUser = new ApplicationDbContext();
        // GET: DonHangs
        [Authorize]
        /*        public ActionResult Index(int? page)
                {
                    if (!AuthAdmin())
                        return RedirectToAction("Error401", "Admin");
                    var all_donHang = data.DonHangs.ToList();
                    //ViewBag.Keyword = searchString;

                    int pageSize = 10;
                    int pageNum = page ?? 1;
                    return View(all_donHang.OrderByDescending(p => p.ngayDat).ToPagedList(pageNum, pageSize));

                }*/

        public ActionResult Index()
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            var all_donHang = data.DonHangs.ToList();
            //ViewBag.Keyword = searchString;
            return View(all_donHang.OrderByDescending(p => p.id_DH));

        }

        // GET: DonHangs/Details
        public ActionResult Details(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.LinQ.DonHang donHang = data.DonHangs.FirstOrDefault(d => d.id_DH == id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            List<Models.CTDH> ctdh = db.CTDH.Where(c => c.id_DH == donHang.id_DH).ToList();
            DonHangViewModel donHangViewModel = new DonHangViewModel()
            {
                DonHang = donHang,
                CTDH = ctdh
            };
            return View(donHangViewModel);
        }



        // GET: DonHangs/Create
        public ActionResult Create()
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            ViewBag.MaKH = new SelectList(data.Users, "Id", "Email");
            return View();
        }

        // POST: DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_DH,ngayDat,ngayGiao,trangThaiThanhToan,trangThaiGiaoHang,phuongThucThanhToan,tongTien,diaChiGiao,id_User,id_Voucher")] Models.DonHang donHang)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.DonHang.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donHang);
        }
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.DonHang donHang = db.DonHang.Find(id);

            var user = data.Users.Where(p => p.Id == donHang.id_User).FirstOrDefault();
            ViewBag.Email = user.Email;
            ViewBag.SDT = user.PhoneNumber;
            ViewBag.TenKH = user.FullName;
            ViewBag.DiaChi = user.Address;

            //DonHangViewModel donHangViewModel = data.DonHangs.Where(p => p.MaDH == id).FirstOrDefault();
            if (donHang == null)
            {
                return HttpNotFound();
            }
            //  ViewBag.MaKH = new SelectList(data.AspNetUsers, "Id", "Email");
            return View(donHang);
        }

        // POST: DonHangs/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_DH,ngayDat,ngayGiao,trangThaiThanhToan,trangThaiGiaoHang,phuongThucThanhToan,tongTien,diaChiGiao,id_User,id_Voucher")] Models.DonHang donHang)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                var editdonHang = db.DonHang.Where(p => p.id_DH == donHang.id_DH).FirstOrDefault();
                //.Entry(donHang).State = EntityState.Modified;
                editdonHang.trangThaiGiaoHang = donHang.trangThaiGiaoHang;
                editdonHang.trangThaiThanhToan = donHang.trangThaiThanhToan;
                editdonHang.ngayGiao = donHang.ngayGiao;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donHang);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /*[Authorize]
        public ActionResult DoanhThu(int? page)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            var all_donHang = data.DonHangs.Where(t => t.trangThaiThanhToan == true && t.trangThaiGiaoHang.ToString() == "1").ToList();
            int pageSize = 7;
            int pageNum = page ?? 1;
            return View(all_donHang.ToPagedList(pageNum, pageSize));
        }*/
        [Authorize]
        public ActionResult DoanhThu()
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            var all_donHang = data.DonHangs.Where(t => t.trangThaiThanhToan == true && t.trangThaiGiaoHang.ToString() == "1").ToList();
            
            return View(all_donHang);
        }
        [Authorize]
        public FileResult Export()
        {
            DataTable dt = new DataTable("Grib");
            dt.Columns.AddRange(new DataColumn[] {
                new DataColumn("STT"),
                new DataColumn("Ngày"),
                new DataColumn("Doanh Thu"),
            }); ;
            var emps = data.DonHangs.Where(t => t.trangThaiThanhToan == true && t.trangThaiGiaoHang == '1').GroupBy(p => p.ngayDat).Distinct().Select(g => new
            {
                Pla = String.Format("{0:dd/MM/yyyy}", g.Key).ToString(),
                Total = g.Sum(t => t.tongTien)
            });
            int i = 1;
            foreach (var emp in emps)
            {
                dt.Rows.Add(i++, emp.Pla, String.Format("{0:0,0}", emp.Total) + " VNĐ");
            }
            dt.Rows.Add();
            dt.Rows.Add("", "Tổng Doanh Thu", String.Format("{0:0,0}", emps.Sum(p => p.Total)) + " VNĐ");
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Doanh-Thu.xlsx");
                }
            }
        }

        public bool AuthAdmin()
        {
            var user = dataUser.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            if (user == null)
                return false;
            var userExist = user.Roles.FirstOrDefault(r => r.UserId == user.Id);
            if (userExist == null)
                return false;
            if (userExist.RoleId != "1")
                return false;
            return true;
        }

        public ActionResult XemDonMua()
        {

            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("Login", "Account");
            }

            ApplicationUser userLogin = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            List<Models.LinQ.DonHang> all_donHang = data.DonHangs.Where(p => p.id_User == userLogin.Id).ToList();
            ViewBag.numberDonHang = all_donHang.Count; //  count tất cả đơn hàng

            List<Models.LinQ.DonHang> all_donHangDangGiao = data.DonHangs.Where(p => p.trangThaiGiaoHang.ToString() == "0" && p.id_User == userLogin.Id).ToList();
            ViewBag.numberDonHangDangGiao = all_donHangDangGiao.Count;

            List<Models.LinQ.DonHang> all_donHangDaGiao = data.DonHangs.Where(p => p.trangThaiGiaoHang.ToString() == "1" && p.id_User == userLogin.Id).ToList();
            ViewBag.numberDonHangDaGiao = all_donHangDaGiao.Count;

            List<Models.LinQ.DonHang> all_donHangDaHuy = data.DonHangs.Where(p => p.trangThaiGiaoHang.ToString() == "2" && p.id_User == userLogin.Id).ToList();
            ViewBag.numberDonHangDaHuy = all_donHangDaHuy.Count;

            List<Models.LinQ.CTDH> all_chiTietDonHang = data.CTDHs.ToList();
            DonHangViewList donHangViewList = new DonHangViewList()
            {
                listDonHang = all_donHang,
                listDonHangDaGiao = all_donHangDaGiao,

WebsiteKinhDoanhCayCanh/Views/DonHangs/Create.cshtml
@model WebsiteKinhDoanhCayCanh.Models.DonHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2>Thêm đơn hàng mới</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Đơn hàng</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <strong class="control-label col-md-2">Trang thái giao hàng</strong>
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.TrangThaiGiaoHang)
                                @Html.ValidationMessageFor(model => model.TrangThaiGiaoHang, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <strong class="control-label col-md-2">Ngày đặt</strong>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <strong class="control-label col-md-2">Ngày giao</strong>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <strong class="control-label col-md-2">Khách hàng</strong>
                        <div class="col-md-10">
                            @Html.DropDownList("MaKH", null, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm đơn hàng" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

            <div>
                @Html.ActionLink("Trở về", "Index")
            </div>
        </div>
    </main>
</div>

WebsiteKinhDoanhCayCanh/Views/DonHangs/Delete.cshtml
@model WebsiteKinhDoanhCayCanh.Models.LinQ.DonHang
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4" style=" margin-top:20px;">

            <h2>Xóa đơn hàng</h2>

            <h3>Bạn có chắc chắn muốn xóa?</h3>
            <div>
                <h4>Đơn hàng</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Trạng thái giao hàng
                    </dt>

                    <dd>
                        @if (Model.TrangThaiGiaoHang == true)
                        {
                            <label class="list-box tri-state" id="TrangThaiGiaoHang" name="TrangThaiGiaoHang">
                                <a value="true">Đã giao</a>
                            </label> }
                        else
                        {
                            <label class="list-box tri-state" id="TrangThaiGiaoHang" name="TrangThaiGiaoHang">
                                <a value="true">Chưa giao</a>
                            </label>}
                    </dd>
                    <dt class="col-md-2">
                        Trạng thái thanh toán
                    </dt>
                    <dd class="col-md-10">
                        @if (Model.TrangThaiThanhToan == true)
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan">
                                <a value="true">Đã thanh toán</a>
                            </label> }
                        else
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan">
                                <a value="true">Chưa thanh toán</a>
                            </label>}
                    </dd>
                    <dt>
                        Ngày đặt
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NgayDat)
                    </dd>

                    <dt>
                        Ngày giao
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NgayGiao)
                    </dd>

                    <dt>
                        Email
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AspNetUser.Email)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa" class="btn btn-danger" />
                        <a class="btn btn-danger" href='@Url.Action("Index", "DonHangs")' style="margin:10px 0px;">
                            Trở về
                        </a>
                    </div>}
            </div>
        </div>
    </main>
</div>

WebsiteKinhDoanhCayCanh/Views/DonHangs/Details.cshtml
@model WebsiteKinhDoanhCayCanh.Models.OtherModels.DonHangViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    dl dt {
        padding-left: 15% !important;
        text-align: start;
        min-width: 40%;
    }

    dl dd {
        text-align: start;
        min-width: 50%;
        max-width: 60% !important;
    }

    tr td {
        text-align: center;
        vertical-align:middle;
    }
    tr th {
        text-align: center;
        vertical-align: middle;
    }
</style>
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4" style=" margin-top: 20px; margin-bottom: 75px;">
            <p style="position:fixed">
                <a class="btn btn-info" href='@Url.Action("Index", "DonHangs")' style="margin:10px 0px;">
                    Trở về
                </a>
            </p>
            <div class="d-flex justify-content-center align-items-center flex-column">
                <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: forestgreen;">Thông Tin Đơn hàng</h2>
                <hr />
                <dl class="dl-horizontal" style="display:flex;flex-wrap:wrap;justify-content:center ;width:65%">
                    <dt class="col-md-2">
                        Mã đơn hàng:
                    </dt>
                    <dd class="col-md-10" style="font-weight:bold">
                        @Html.DisplayFor(model => model.DonHang.id_DH)
                    </dd>
                    <dt class="col-md-2">
                        Ngày đặt:
                    </dt>
                    <dd class="col-md-10" style="font-weight:bold">
                        @Convert.ToDateTime(Model.DonHang.ngayDat).ToString("dd-MM-yyyy")
                    </dd>

                    <dt class="col-md-2">
                        Ngày giao:
                    </dt>
                    <dd class="col-md-10" style="font-weight:bold">
                        @Convert.ToDateTime(Model.DonHang.ngayGiao).ToString("dd-MM-yyyy")
                    </dd>
                    <dt class="col-md-2">
                        Địa chỉ giao hàng:
                    </dt>
                    <dd class="col-md-10" style="font-weight:bold">
                        @Html.DisplayFor(model => model.DonHang.diaChiGiao)
                    </dd>
                    <dt class="col-md-2">
                        Trạng thái giao hàng:
                    </dt>
                    <dd class="col-md-10">
                        @if (Model.DonHang.trangThaiGiaoHang.ToString() == "0")
                        {
                            <span style="color:orange;font-weight:bold">Đang giao</span>
                        }
                        else
                        {
                            if (Model.DonHang.trangThaiGiaoHang.ToString() == "1")
                            {
                                <span style="color:limegreen;font-weight:bold">Đã giao</span>
                            }
                            else
                            {
                                <span style="color:red;font-weight:bold">Đã hủy đơn</span>
                            }
                        }
                    </dd>
                    <dt class="col-md-2">
                        Trạng thái thanh toán:
                    </dt>
                    <dd class="col-md-10">
                        @if (Model.DonHang.trangThaiThanhToan == true)
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan">
                                <a style="font-weight:bold;color:limegreen" value="true">Đã thanh toán</a>
                            </label>
                        }
                        else
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan" style="font-weight:bold;color:red">
                                <a style="font-weight:bold;color:red" value="true">Chưa thanh toán</a>
                            </label>
                        }
                    </dd>
                    <dt class="col-md-2">
                        Phương thức thanh toán:
                    </dt>
                    <dd class="col-md-10">
                        @if (Model.DonHang.phuongThucThanhToan == '0')
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan">
                                <a style="font-weight:bold; color:limegreen" value="true">Thanh toán khi nhận hàng</a>
                            </label>
                        }
                        else
                        {
                            <label class="list-box tri-state" id="TrangThaiThanhToan" name="TrangThaiThanhToan" style="font-weight:bold;color:red">
                                <a style="font-weight: bold; color: limegreen; " value="true">Thanh toán online</a>
                            </label>
                        }
                    </dd>
                    <dt class="col-md-2">
                        Tổng tiền:
                    </dt>
                    <dd class="col-md-10" style="color:red;font-weight:bold">
                        @String.Format("{0:0,0}", Model.DonHang.tongTien) VNĐ
                    </dd>

                    <dt><hr /></dt>
                    <dd><hr /></dd>
                    <dt class="col-md-2">
                        Tên KH:
                    </dt>
                    <dd class="col-md-10">
                        @Html.DisplayFor(model => model.DonHang.User.FullName)
                    </dd>
                    <dt class="col-md-2">
                        Email:
                    </dt>
                    <dd class="col-md-10">
                        @Html.DisplayFor(model => model.DonHang.User.Email)
                    </dd>

                    <dt class="col-md-2">
                        Số điện thoại:
                    </dt>
                    <dd class="col-md-10">
                        @Html.DisplayFor(model => model.DonHang.User.PhoneNumber)
                    </dd>

                    <dt class="col-md-2">
                        Địa chỉ:
                    </dt>
                    <dd class="col-md-10">
                        @Html.DisplayFor(model => model.DonHang.User.Address)
                    </dd>


                </dl>
            </div>
            <div>
                @Html.ActionLink("Xuất hóa đơn", "Index", "Report", new { id = Model.DonHang.id_DH }, new { @class = "btn btn-success" })
                <hr />
                <table class="table table-bordered table-success">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                Tên sản phẩm
                            </th>
                            <th>
                                Hình ảnh
                            </th>
                            <th>
                                Số lượng
                            </th>
                            <th>
                                Đơn giá
                            </th>
                            <th>
                                Giảm giá
                            </th>
                            <th>
                                Thành tiền
                            </th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        @foreach (var item in Model.CTDH)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SanPham.tenSP)
                                </td>

                                <td>
                                    <img src="@item.SanPham.HinhAnhSP.Where(p => p.id_SP == item.id_SP).FirstOrDefault().duongDan" alt="Alternate Text" width="100" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.soLuong)
                                </td>
                                <td><strong>@String.Format("{0:0,0}", item.SanPham.gia) VNĐ</strong> </td>
                                <td><strong>@String.Format("{0:0,0}", item.SanPham.phanTramGiamGia) %</strong> </td>
                                <td>
                                    <strong style="color:red"> @String.Format("{0:0,0}", item.thanhTien) VNĐ</strong>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </main>
</div>

WebsiteKinhDoanhCayCanh/Views/DonHangs/DoanhThu.cshtml
@*﻿@model PagedList.PagedList<WebsiteKinhDoanhCayCanh.Models.LinQ.DonHang>
@using PagedList.Mvc;*@
@model IEnumerable<WebsiteKinhDoanhCayCanh.Models.LinQ.DonHang>
@{
    ViewBag.Title = "DoanhThu";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    dl dt {
        padding-left: 10% !important;
        text-align: start;
        min-width: 40%;
    }

    dl dd {
        text-align: start;
        min-width: 50%;
        max-width: 50% !important;
    }

    tr td {
        text-align: center;
        vertical-align: middle;
    }

    tr th {
        text-align: center;
        vertical-align: middle;
    }

    /* Css for table*/
    table.dataTable thead .sorting:after,
    table.dataTable thead .sorting:before,
    table.dataTable thead .sorting_asc:after,
    table.dataTable thead .sorting_asc:before,
    table.dataTable thead .sorting_asc_disabled:after,
    table.dataTable thead .sorting_asc_disabled:before,
    table.dataTable thead .sorting_desc:after,
    table.dataTable thead .sorting_desc:before,
    table.dataTable thead .sorting_desc_disabled:after,
    table.dataTable thead .sorting_desc_disabled:before {
        bottom: .5em;
    }

    div.dataTables_length label {
        width: 460px;
        float: left;
        text-align: left;
    }

    div.dataTables_length select {
        width: 75px;
    }

    div.dataTables_filter label {
        float: right;
        width: 460px;
    }

    div.dataTables_info {
        padding-top: 8px;
    }

    div.dataTables_paginate {
        float: right;
        margin: 0;
    }

    table {
        margin: 1em 0;
        clear: both;
    }

        table thead tr th:last-child {
            vertical-align: middle;
            text-align: center;
        }

        table tbody tr td:last-child {
            vertical-align: middle;
            text-align: center;
        }

            table tbody tr td:last-child:hover {
                cursor: pointer
            }
</style>
<div id="layoutSidenav_content">
    <main>
        <h2 style="margin: 10px; text-align: center; margin-top: 20px; font-weight: bold; color: forestgreen;text-transform:capitalize">Doanh thu theo ngày</h2>
        <br />
        <div class="container-fluid px-4" style="margin-bottom: 75px;">
            @using (Html.BeginForm("Export", "DonHangs", FormMethod.Post))
            {
        <input type="submit" value="Xuất Excel" class="btn btn-success">}
            <br />
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Bảng thông tin thống kê doanh thu
                </div>
                <br />
                <table id="datatablesSimple" class="table table-bordered table-success">
                    <thead>
                        <tr>
                            <th class="text-center">STT</th>
                            <th class="text-center">
                                Ngày
                            </th>
                            <th class="text-center">
                                Doanh Thu
                            </th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        @{ int i = 0;
                        foreach (var item in Model.GroupBy(y => y.ngayDat).Distinct().Select(g => new { Pla = g.Key, Total = g.Sum(t => t.tongTien) }))
                        {
                            i++;
                            <tr>
                                <td>
                                    @i
                                </td>
                                <td>
                                    @String.Format("{0:dd/MM/yyyy}", item.Pla)
                                </td>
                                <td>
                                    <strong style="color:red;font-weight:bold">@String.Format("{0:0,0}", item.Total) VNĐ</strong>
                                </td>
                            </tr> } }
                    </tbody>
                </table>
                </div>            
            </div>
</main>
</div>